
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Properties;
import javax.mail.*;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.MessageFormat;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akram
 */
public class enseignant extends javax.swing.JFrame {
Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    ResultSet rs2=null;
    PreparedStatement pst2=null;
    /**
     * Creates new form enseignant
     */
    public enseignant() {
        initComponents();
        setLocationRelativeTo(null);
        conn= connect.ConnecrDb();
        Update_table();
        Fillcombo();
    }
    private void Update_table(){
            try{
            
            String sql = "select Jour,Section,Matiere,Salle,Heure,Enseignant from Exam";
            pst = conn.prepareStatement(sql);
            rs= pst.executeQuery();
            Table_exam.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        }
    public void close(){
    WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
}
    private void Fillcombo() {
        try{
            String sql = "select * from enseignant ";
            pst = conn.prepareStatement(sql);
            rs= pst.executeQuery();
            while(rs.next()){
            String name=rs.getString("Nom");
            ens.addItem(name);
            }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_exam = new javax.swing.JTable();
        ens = new javax.swing.JComboBox<>();
        btn_print = new javax.swing.JButton();
        Sessions = new javax.swing.JComboBox<>();
        txt_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_prenom = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bnt_suppr = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_exam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Table_exam);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 482, 365));

        ens.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                ensPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        ens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ensMouseClicked(evt);
            }
        });
        ens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ensActionPerformed(evt);
            }
        });
        getContentPane().add(ens, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 215, 134, -1));

        btn_print.setText("Imprimer");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });
        getContentPane().add(btn_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 100, -1));

        Sessions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principale ", "Controle" }));
        getContentPane().add(Sessions, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 120, -1));
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 315, 199, -1));

        jLabel2.setText("Nom:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 318, -1, -1));
        getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 404, 199, -1));

        jLabel3.setText("Mail:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 407, -1, -1));

        jButton1.setText("Ajout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 120, -1));

        jLabel4.setText("Prenom:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 360, -1, -1));
        getContentPane().add(txt_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 357, 199, -1));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 271, 199, -1));

        jLabel5.setText("id:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 274, 30, -1));

        jButton2.setText("Mail");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 100, -1));

        jButton3.setText("Mail Page");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 120, -1));

        jLabel6.setText("Enseignant:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 221, -1, -1));

        bnt_suppr.setText("Supprimer");
        bnt_suppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_supprActionPerformed(evt);
            }
        });
        getContentPane().add(bnt_suppr, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 460, 110, -1));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akram\\Desktop\\homebtn.jpg")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 70, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Akram\\Desktop\\backyess.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ensActionPerformed

    private void ensPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_ensPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String tmp=(String)ens.getSelectedItem();
         String sql = "select Jour,Section,Matiere,Salle,Heure,Enseignant from Exam where Enseignant=?";
         String sql2="select * from enseignant where Nom=?";
          try{
            
           
            pst = conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs= pst.executeQuery();
            pst2 = conn.prepareStatement(sql2);
            pst2.setString(1, tmp);
            rs2= pst2.executeQuery();
            Table_exam.setModel(DbUtils.resultSetToTableModel(rs));
            if(rs.next()){
            Table_exam.setModel(DbUtils.resultSetToTableModel(rs));
           
            }
            if(rs2.next()){
            String add= rs2.getString("id_enseignant");
            txt_id.setText(add);
            String add1= rs2.getString("Nom");
            txt_name.setText(add1);
            String add2= rs2.getString("Prenom");
            txt_prenom.setText(add2);
            String add3= rs2.getString("Mail");
            txt_mail.setText(add3);
            
           
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
         
    }//GEN-LAST:event_ensPopupMenuWillBecomeInvisible

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        MessageFormat header = new MessageFormat("Calendrier des Examens Session:"+Sessions.getSelectedItem());
         MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try{
           Table_exam.print(JTable.PrintMode.NORMAL,header,footer);
        }catch (java.awt.print.PrinterException e){
        System.err.format("Impression impossible",e.getMessage());
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
         String sql ="Insert into enseignant (id_enseignant,Nom,Prenom,Mail) values(?,?,?,?)";
         pst=conn.prepareStatement(sql); 
         pst.setString(1,txt_id.getText());
         pst.setString(2,txt_name.getText());
         pst.setString(3,txt_prenom.getText());
         pst.setString(4,txt_mail.getText());
         pst.execute();
                 JOptionPane.showMessageDialog(null, "Enseignant Ajouter");  
                 rs.close();
                pst.close();

        }catch(Exception e)
        {
             
            JOptionPane.showMessageDialog(null, e);        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Properties props= new Properties();
        props.put("mail.smtp.host","smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth","true" );
        props.put("mail.smtp.port","465" );
        Session session= Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication("barhoumi1393@gmail.com", "143244bm");
                }
                });
        try{
        Message message= new MimeMessage(session);
        message.setFrom(new InternetAddress("barhoumi1393@gmail.com"));
        message.setRecipients (Message.RecipientType.TO, InternetAddress.parse("barhoumi1393@gmail.com"));
        message.setSubject("Calendrier des examens");
        message.setText("c'est ESPRIM");
      
        Transport.send(message);
        JOptionPane.showMessageDialog(null,"Message envoyer");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
                

               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
          String url="https://mail.google.com/mail/ca/u/0/#inbox?compose=new";
          java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bnt_supprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_supprActionPerformed
        // TODO add your handling code here
        int p =JOptionPane.showConfirmDialog(null, "Est ce que vous etes sur de supprimer?","Supprimer",JOptionPane.YES_NO_OPTION);
        if(p==0){
            try{
                String sql ="Delete from enseignant where Nom=? ";
                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_name.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Enseigant supprimer");

            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
            Update_table();
        }
    }//GEN-LAST:event_bnt_supprActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        choix ch=new choix();
        ch.setVisible(true);
        close();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ensMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ensMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enseignant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Sessions;
    private javax.swing.JTable Table_exam;
    private javax.swing.JButton bnt_suppr;
    private javax.swing.JButton btn_print;
    private javax.swing.JComboBox<String> ens;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_prenom;
    // End of variables declaration//GEN-END:variables
}
